

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify"
import { ThemeProvider } from '@/components/ThemeProvider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="/js/fontawesome.js" defer />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-accent  min-h-screen flex flex-col justify-between `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className=" w-full ">
            <Header />
            <ToastContainer position='bottom-center' autoClose={5000} theme="dark" />
          </div>
          {children}
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
